version: '3'
services:
  db:
    image: mariadb:10.6
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    ports:
      - "127.0.0.1:3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:?definir dans docker-sqlite/.env}
      - MYSQL_DATABASE=${MYSQL_DATABASE:?}
      - MYSQL_USER=${MYSQL_USER:?}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:?}
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=db
    depends_on:
      - db
    restart: always
    
  api:
    environment:
      - DB_HOST=db
      - DB_NAME=${MYSQL_DATABASE:?}
      - DB_USER=${MYSQL_USER:?}
      - DB_PASS=${MYSQL_PASSWORD:?}
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - ./api:/var/www/html
    ports:
      - "5001:80"
    depends_on:
      - db
    restart: always
