version: '3'
services:
  sqlite:
    build: .
    volumes:
      - ./data:/data
    environment:
      - SQLITE_DATABASE=health.db
    restart: always

  sqlite-web:
    image: coleifer/sqlite-web
    volumes:
      - ./data:/data
    ports:
      - "8080:8080"
    environment:
      - SQLITE_DATABASE=health.db
    depends_on:
      - sqlite
    restart: always
