apiVersion: 1

datasources:
  - name: "MariaDB-Prod"
    type: mysql
    access: proxy
    isDefault: false
    url: "db:3306"
    database: "healthtracker"
    user: "healthuser"
    jsonData:
      tlsAuth: false
      tlsSkipVerify: false
    secureJsonData:
      password: $__env{HEALTH_DB_PASS}
